### ISSUE TITLE
RUL estimation reslut

### ISSUE THREAD

**Issue by UCAS-Vincent** [LahiruJayasinghe/RUL-Net#2]
The final result predicted by the program is an estimate of the RUL of each aircraft engine, or an estimate of the RUL of FD001-004.

**Comment by LahiruJayasinghe** [comment]
Dear Wen Han,

This CMAPSS dataset is a simulated dataset created by NASA. This dataset is made of four sub-datasets (FD001-FD004) which consist of four different conditions (two different operation conditions and two different fault conditions). More details can be found in the attached document herewith. 

For the next question, solving for CMAPSS dataset means you have to solve for sub-datasets. That means for a given condition of an engine (an operation and a fault condition) it will predict the RUL value. Therefore, our method focused on estimating the RUL of FD001-FD004 (sub-datasets) separately.

Please note that RUL-Net on github is not a 100% replica of our paper. It's an attempt to release our deep learning model to researchers to help them in their predictive maintenance researches.

Thanks and Regards,
Lahiru

https://github.com/LahiruJayasinghe/RUL-Net/blob/master/CMAPSSData/readme.txt
