### ISSUE TITLE
How long did you spend on training the network?

### ISSUE THREAD

**Issue by zacario-li** [LahiruJayasinghe/RUL-Net#3]
How long did you spend on training the network?

**Comment by LahiruJayasinghe** [comment]
Actually it's not based on the time, I always did early stopping to prevent overfitting. Therefore, I haven't had a specific time duration.

**Comment by zacario-li** [comment]
> Actually it's not based on the time, I always did early stopping to prevent overfitting. Therefore, I haven't had a specific time duration.

Thank you.
